/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import Interface.InterfaceAset;
import Server.Aset;
import Server.Server;
import com.mysql.jdbc.Statement;
import java.awt.HeadlessException;
import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.event.TableModelEvent;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dyota
 */
public class guiApp extends javax.swing.JFrame {

    /**
     * Creates new form guiApp
     */
    public guiApp() {
        initComponents();
        try {
            tampildata();
            
            comboKategori.setModel(new DefaultComboBoxModel<>(new String[]{
                "Pilih Kategori", "Furniture", "Alat Tulis Kantor", "Alat Makan", "Transport","Lain-lain"
            }));
            
        }catch (NotBoundException ex) {
            System.out.println("Error Bound");
            Logger.getLogger(guiApp.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            System.out.println("Error URL");
            Logger.getLogger(guiApp.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            System.out.println("ErrorRemote");
            Logger.getLogger(guiApp.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }
    public void tampildata() throws NotBoundException, MalformedURLException, RemoteException{
    
        InterfaceAset ia = (InterfaceAset) Naming.lookup("rmi://localhost:212/rmi");   
        DefaultTableModel model = (DefaultTableModel) tabelAset.getModel();
                
        Object[] row = new Object [8];
        for(Aset aset: ia.getAset()){
            row[0] = aset.getKode_aset();
            row[1] = aset.getNama_aset();
            row[2] = aset.getKategori_aset();
            row[3] = aset.getTanggal_terima();
            row[4] = aset.getBataspemakaian();
            row[5] = aset.getMasapemakaian();
            row[6] = aset.getNilaiaset();
            row[7] = aset.getPenyusutan();
            model.addRow(row);
        
    }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTambah2 = new javax.swing.JButton();
        panel = new javax.swing.JPanel();
        txtKodeBarang = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        labelKodeBarang = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelAset = new javax.swing.JTable();
        editKodeAset = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        labelKodeAset = new javax.swing.JLabel();
        editNamaAset = new javax.swing.JTextField();
        labelNamaAset = new javax.swing.JLabel();
        labelKategori = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        editTanggalTerima = new javax.swing.JTextField();
        LabelBatasPemakai = new javax.swing.JLabel();
        editBatasPemakai = new javax.swing.JTextField();
        labelTanggalTerima = new javax.swing.JLabel();
        labelBulan = new javax.swing.JLabel();
        labelMasaPemakai = new javax.swing.JLabel();
        editMasaPemakai = new javax.swing.JTextField();
        labelNilaiAset = new javax.swing.JLabel();
        editNilaiAset = new javax.swing.JTextField();
        labelPenyusutan = new javax.swing.JLabel();
        editPenyusutan = new javax.swing.JTextField();
        comboKategori = new javax.swing.JComboBox<>();
        labelJudul = new javax.swing.JLabel();

        btnTambah2.setText("Tambah");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCari.setText("Cari");

        labelKodeBarang.setText("Kode Aset");

        tabelAset.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Aset", "Nama Aset", "Kategori Aset", "Tanggal Terima", "Batas Pemakaian", "Masa Pemakaian (bln)", "Nilai Aset", "Penyusutan"
            }
        ));
        tabelAset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelAsetMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelAset);

        editKodeAset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editKodeAsetActionPerformed(evt);
            }
        });

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");

        labelKodeAset.setText("Kode Aset");

        labelNamaAset.setText("Nama Aset");

        labelKategori.setText("Kategori");

        LabelBatasPemakai.setText("Batas Pemakaian");

        labelTanggalTerima.setText("Tanggal Terima");

        labelBulan.setText("bulan");

        labelMasaPemakai.setText("Masa Pemakaian");

        labelNilaiAset.setText("Nilai Aset       Rp");

        labelPenyusutan.setText("Penyusutan");

        comboKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboKategori.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboKategoriItemStateChanged(evt);
            }
        });
        comboKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboKategoriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(labelKodeBarang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtKodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelKategori)
                                .addComponent(labelNamaAset, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelKodeAset, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(editKodeAset, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(editNamaAset, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(comboKategori, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(81, 81, 81)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelLayout.createSequentialGroup()
                                            .addGap(2, 2, 2)
                                            .addComponent(LabelBatasPemakai, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(4, 4, 4))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                                            .addComponent(labelTanggalTerima, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                    .addGroup(panelLayout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(labelMasaPemakai, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)))
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(panelLayout.createSequentialGroup()
                                        .addComponent(editMasaPemakai, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(labelBulan))
                                    .addComponent(editTanggalTerima)
                                    .addComponent(editBatasPemakai, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                                .addGap(114, 114, 114)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelNilaiAset, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelPenyusutan, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(editPenyusutan)
                                    .addComponent(editNilaiAset, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)))))))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelKodeBarang)
                        .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtKodeBarang, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editNilaiAset, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNilaiAset))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editPenyusutan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelPenyusutan)))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editTanggalTerima, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTanggalTerima)
                            .addComponent(editKodeAset, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelKodeAset))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editBatasPemakai, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelBatasPemakai)
                            .addComponent(editNamaAset, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNamaAset))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editMasaPemakai, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelMasaPemakai)
                            .addComponent(labelBulan)
                            .addComponent(labelKategori)
                            .addComponent(comboKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        labelJudul.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        labelJudul.setText("Daftar Aset");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelJudul))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(labelJudul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void clearInput(){
        editKodeAset.setText(null);
        editNamaAset.setText(null);
        comboKategori.setSelectedIndex(0);
        editTanggalTerima.setText(null);
        editBatasPemakai.setText(null);
        editMasaPemakai.setText(null);
        editNilaiAset.setText(null);
        editPenyusutan.setText(null);
    }
    
    public void insertData() throws SQLException{
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_aset","root","");
            Statement insertStatement = (Statement) con.createStatement();
            
            String inKode = editKodeAset.getText();
            String inNamaAs = editNamaAset.getText();
            String inKategori = comboKategori.getSelectedItem().toString();
            Date inTglTerima = Date.valueOf(editTanggalTerima.getText());
            String inBatas = editBatasPemakai.getText();
            String inMasa = editMasaPemakai.getText();
            int inNilaiAs = Integer.parseInt(editNilaiAset.getText());
            int inPenyusutan = Integer.parseInt(editPenyusutan.getText());
            
            InterfaceAset ia = (InterfaceAset) Naming.lookup("rmi://localhost:212/rmi");
            String insertResult = ia.Insert(inKode, inNamaAs, inKategori, inTglTerima, inBatas, inMasa, inNilaiAs, inPenyusutan);
            
            DefaultTableModel defTable = (DefaultTableModel) tabelAset.getModel();
            defTable.setRowCount(0);
            tampildata();
            
            JOptionPane.showMessageDialog(null, insertResult,"Aset ditambahkan", JOptionPane.INFORMATION_MESSAGE);
            clearInput();         
            
        }catch(HeadlessException | ClassNotFoundException | NumberFormatException | MalformedURLException | NotBoundException | RemoteException | SQLException e){
            JOptionPane.showMessageDialog(null, e,"Error", JOptionPane.ERROR_MESSAGE);
            
        }
    
    }
    
    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        
       
        try {
            insertData();
            
        } catch (SQLException ex) {
            Logger.getLogger(guiApp.class.getName()).log(Level.SEVERE, null, ex);
        }
                       
            
        
        
    }//GEN-LAST:event_btnTambahActionPerformed

    private void editKodeAsetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editKodeAsetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editKodeAsetActionPerformed

    private void comboKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboKategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboKategoriActionPerformed

    private void comboKategoriItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboKategoriItemStateChanged
        //String comboKat = 
    }//GEN-LAST:event_comboKategoriItemStateChanged

    private void tabelAsetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelAsetMouseClicked
        int ambil = tabelAset.getSelectedRow();
         DefaultTableModel model = (DefaultTableModel) tabelAset.getModel();
         editKodeAset.setText(model.getValueAt(ambil,0).toString());
         editNamaAset.setText(model.getValueAt(ambil,1).toString());
         editMasaPemakai.setText(model.getValueAt(ambil,5).toString());
         editNilaiAset.setText(model.getValueAt(ambil,6).toString());
         editPenyusutan.setText(model.getValueAt(ambil,7).toString());
         editBatasPemakai.setText(model.getValueAt(ambil,4).toString());
         editTanggalTerima.setText(model.getValueAt(ambil,3).toString());
         comboKategori.setSelectedItem(model.getValueAt(ambil,2).toString());
    }//GEN-LAST:event_tabelAsetMouseClicked

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        try {   
            
            InterfaceAset ya = (InterfaceAset) Naming.lookup("rmi://localhost:212/rmi");
            String kode = editKodeAset.getText();
            String nama = editNamaAset.getText();
            String masa = editMasaPemakai.getText();
            int nilai = Integer.parseInt(editNilaiAset.getText());
            int penyusutan = Integer.parseInt(editPenyusutan.getText());
            String batas = editBatasPemakai.getText();
            Date tanggal = Date.valueOf(editTanggalTerima.getText());
            String kategori = comboKategori.getSelectedItem().toString();
            
            String update = ya.Update(kode, nama, kategori, tanggal, batas, masa, nilai, penyusutan);
            
            DefaultTableModel defTable = (DefaultTableModel) tabelAset.getModel();
            defTable.setRowCount(0);
            tampildata();
            JOptionPane.showMessageDialog(null,update,"Aset",JOptionPane.INFORMATION_MESSAGE);
            clearInput();
            
        } catch (NotBoundException ex) {
            Logger.getLogger(guiApp.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(guiApp.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(guiApp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(guiApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(guiApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(guiApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(guiApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new guiApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelBatasPemakai;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnTambah2;
    private javax.swing.JComboBox<String> comboKategori;
    private javax.swing.JTextField editBatasPemakai;
    private javax.swing.JTextField editKodeAset;
    private javax.swing.JTextField editMasaPemakai;
    private javax.swing.JTextField editNamaAset;
    private javax.swing.JTextField editNilaiAset;
    private javax.swing.JTextField editPenyusutan;
    private javax.swing.JTextField editTanggalTerima;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelBulan;
    private javax.swing.JLabel labelJudul;
    private javax.swing.JLabel labelKategori;
    private javax.swing.JLabel labelKodeAset;
    private javax.swing.JLabel labelKodeBarang;
    private javax.swing.JLabel labelMasaPemakai;
    private javax.swing.JLabel labelNamaAset;
    private javax.swing.JLabel labelNilaiAset;
    private javax.swing.JLabel labelPenyusutan;
    private javax.swing.JLabel labelTanggalTerima;
    private javax.swing.JPanel panel;
    private javax.swing.JTable tabelAset;
    private javax.swing.JTextField txtKodeBarang;
    // End of variables declaration//GEN-END:variables
}
